FROM node:9.4.0

# Create a user app to run the (guess what) app
RUN useradd --user-group --create-home --shell /bin/false app

ENV HOME=/home/app

# We prepare for npm install,
# first copy package.json from frontend sibling repo
COPY ./frontend/package.json $HOME/frontend/

# docker always copies as root, does not honor USER
RUN chown -R app:app $HOME/*

USER app

WORKDIR $HOME/frontend
# RUN npm install

EXPOSE 8080